{\rtf1\ansi\ansicpg1252\cocoartf2511
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fmodern\fcharset0 Courier;\f1\fnil\fcharset129 AppleSDGothicNeo-Regular;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs26 \cf0 \expnd0\expndtw0\kerning0
theme: jekyll-theme-minimal\
title: 
\f1 \'b5\'f6\'b7\'af\'b4\'d7
\f0  
\f1 \'bd\'ba\'c5\'cd\'b5\'f0
\f0  
\f1 \'c0\'da\'b7\'e1
\f0  
\f1 \'b8\'f0\'c0\'bd}